services:
  fastapi-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      # - MASTER_KEY=your_super_secret_master_key # Uncomment and set your master key here
      - API_TOKEN=${API_TOKEN} # This is currently unused but kept for potential future use
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped
