services:
  fastapi-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      # The MASTER_KEY should be set in a .env file. See README.md for details.
      - MASTER_KEY=${MASTER_KEY}
      - API_TOKEN=${API_TOKEN} # This is currently unused but kept for potential future use
    volumes:
      - ./outputs:/app/outputs
      # Mount the api_keys.txt file to persist user keys across container restarts.
      - ./api_keys.txt:/app/api_keys.txt
    restart: unless-stopped
